name: IslandArchitect
author: ClouriaNetworkDevelopers
authors: [Endermanbugzjfc]
api: 3.0.0
version: 1.0.0
main: Clouria\IslandArchitect\IslandArchitect
website: https://github.com/crnw-dev/IslandArchitect
depend: [SkyBlock]

permissions:
  island-architect:
    default: op
    children:
      island-architect.cmd:
        children:
          island-architect.convert:
            description: Permission to convert a island into JSON island template file