name: IslandArchitect
author: ClouriaNetworkDevelopers
authors: [Endermanbugzjfc]
api: 3.0.0
version: 1.0.0
main: Clouria\WorldBindedShops\WorldBindedShops
website: https://github.com/crnw-dev/IslandArchitect
soft-depend: [SkyBlock]